# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Build Reshift Intellij Plugin

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Java 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew buildPlugin
    - name: Retrieve version
      run: |
        RAW_VERSION=`./gradlew properties | grep version`
        VERSION=`echo "${RAW_VERSION/'version: '/''}"`
        echo ::set-env name=TAG_NAME::$VERSION
